### ISSUE TITLE
Any example how GeoTorch can be tuned for GPU processing?

### ISSUE THREAD

**Issue by Sarwat** [DataSystemsLab/GeoTorchAI#7]

**Comment by kanchanchy** [comment]
Hi Professor @Sarwat. I updated the deep learning example in the Readme file to include deep learning with GPU. In the website documentation, I added a section for deep learning with GPU. https://kanchanchy.github.io/geotorch/coding_examples.html

Also, all the examples available on the website and GitHub repository (under binders and examples folders) include deep learning with both GPU and CPU.
https://github.com/DataSystemsLab/GeoTorch/tree/main/binders
https://github.com/DataSystemsLab/GeoTorch/tree/main/examples
