### ISSUE TITLE
pip install geotorch

### ISSUE THREAD

**Issue by Sarwat** [DataSystemsLab/GeoTorchAI#8]
is there a way GeoTorch / dependencies can be simply installed using pip install. That will make it easy for a lot of people to use it.

**Comment by kanchanchy** [comment]
Yes, I will try it. We need to create an account in PyPI. https://pypi.org/account/register/
Do you want me to create the account? If you want to create the account from Data Systems Lab, please provide me the username and password. @Sarwat

**Comment by Sarwat** [comment]
Please go ahead and create the account

**Comment by kanchanchy** [comment]
Hi Professor @Sarwat, PyPI is not allowing me to upload my package there because they already have a package with the same name. https://pypi.org/project/geotorch/
It's a library for constraint optimization. With pip install geotorch, that library would be installed.

**Comment by Sarwat** [comment]
What about we make it pip install geotorchai or something similar to that.

**Comment by kanchanchy** [comment]
It is possible. Usually, people keep it similar to the library name. There are two options:
1. Changing the name of the library everywhere.
2. The name will remain unchanged as geotorch in the repository codes and documentation. Developers will import it as geotorch in their code, but it will be available on PyPI as geotorchai and can be installed as pip install geotorchai. If you want to go for this option, I need to check whether PyPI accepts it.

**Comment by Sarwat** [comment]
What about we change the package name to SedonaTorch since it integrates with Apache Sedona? (Option 1)

**Comment by kanchanchy** [comment]
I am okay with that, but will we be able to change the repository name?

**Comment by Sarwat** [comment]
Yes, we can!

**Comment by kanchanchy** [comment]
Okay. I can start working on changing the name in the code on a new branch.

**Comment by Sarwat** [comment]
We can also rename it GeoTorchAI if you think that's better. Here are a few suggestions:

SedonaTorch
GeoTorchAI
ST_Torch
GeoTorchLib
GeoAILib

**Comment by Sarwat** [comment]
I trust your judgement. Let's go with GeoTorchAI then!

**Comment by kanchanchy** [comment]
Hi Professor, all changes are ready to be pushed, including the changes for the documentation website. Please let me know when you want the changes to be updated in the repository.

**Comment by Sarwat** [comment]
So, have you changed the library name all over? Shall I go ahead and change the repo name too?

**Comment by kanchanchy** [comment]
Hi Professor,
Yes, the changes have been pushed. I need to change some links after you change the repository name. Also, the name in the logo needs to be changed.

**Comment by kanchanchy** [comment]
Hi Professor, GeoTorchAI can be installed with pip install geotorchai
https://pypi.org/project/geotorchai/

**Comment by MoSarwat** [comment]
Great - did we add the installation guide the project Readme. 
Also, on a side note, the website / examples still has GeoTorch instead of GeoTorchAI

**Comment by kanchanchy** [comment]
I updated the installation instructions. I also replaced geotorch to geotorchai wherever I found the term geotorch in the readme, examples, and website. The project description on PyPI cannot be changed until the next release.
