### ISSUE TITLE
No documentation for embedding new models

### ISSUE THREAD

**Issue by Sarwat** [DataSystemsLab/GeoTorchAI#9]
There is clear documentation on how a contributor can embed new models.

**Comment by kanchanchy** [comment]
Added the instructions for contribution or PR here https://github.com/DataSystemsLab/GeoTorch/blob/main/CONTRIBUTING.md
I also provided a link to this file in the README documentation. https://github.com/DataSystemsLab/GeoTorch#contributing-to-this-project
